### ISSUE TITLE
Uploading resume again and again.

### ISSUE THREAD

**Issue by gobiursus** [madingess/EasyApplyBot#15]
My saved resume will be canceled and re-upload again and again in each application. Can we skip this step?

**Comment by voidbydefault** [comment]
Spot on @ColbySawyer7 . 

@gobiursus, resume upload using `config.yaml` got kucked-up after some changes at LinkedIn (it's not working) so the best way is what @ColbySawyer7 mentioned.

Not an issue. Closing.

**Comment by madingess** [comment]
I believe this has been addressed, as I'm no longer able to reproduce the issue. 

Please reopen with details if you are still finding this to occur!
