### ISSUE TITLE
Phone country code always gets picked wrong

### ISSUE THREAD

**Issue by Kaanis** [madingess/EasyApplyBot#16]
I inserted in the YAML file my country code which is "Italia (+39)" correctly but in the applications always input  Zimbabwe (+263)

![image](https://user-images.githubusercontent.com/85311401/210538571-b0fe7dfa-c953-4f8f-9243-37a57c9aacb8.png)

![image](https://user-images.githubusercontent.com/85311401/210538774-8b2010d4-6b25-431f-a486-fa0d66c62509.png)

**Comment by Kaanis** [comment]
Update: the problem is that I am using the italian value name for the country code field..which is correct in the italian version of LinkedIn but not on the international version of the platform that this script is using.

Value I was using: "Italia (+39)"
Value accepted by the script: "Italy (+39)"

Maybe add this as an improvement

**Comment by madingess** [comment]
Thanks for the report. 

I won't add this functionality as that would involved identifying and adding the translation for every possible country code, present AND future. However, I did add some documentation to the README and config files to clarify this.
