### ISSUE TITLE
Resume not uploaded automatically

### ISSUE THREAD

**Issue by Kaanis** [madingess/EasyApplyBot#17]
Although I have entered the cv correctly in the yaml file, it never loads automatically in the job offers and I am forced to reselect it manually

![image](https://user-images.githubusercontent.com/85311401/210544262-68956ae8-ff9a-4cbc-b1ef-cdd4fbb640dd.png)
![image](https://user-images.githubusercontent.com/85311401/210544317-663ad8eb-ace7-4b31-bd76-39e67318db5f.png)

**Comment by madingess** [comment]
Will you please try removing spaces from your resume file name and confirm whether that fixes the issue?

**Comment by squares88** [comment]
@madingess I have removed spaces from my resume file and getting into the same issue, tried on mac and linux environment. Also maybe as a suggestion, if a resume already uploaded I think it makes sense to make the code to choose already uploaded resume.

**Comment by Akhilesh-Gogikar** [comment]
@squares88 could you please give an example of what you did to solve this?

**Comment by squares88** [comment]
@Akhilesh-Gogikar I added path in this format: C:\User\Folder\File.pdf, it worked simple as that on windows, not sure what path should be for other platforms thou.

**Comment by madingess** [comment]
Thanks for the comments @squares88 .

For those experiencing issue, try using an absolute path with no spaces. 

For example:

- Windows --- C:\User\Folder\File.pdf
- Linux --- /home/Users/Folder/File.pdf

**Comment by madingess** [comment]
Will close this for now due to inactivity from poster. 

If anyone experiences this issue and the above post does not work, please comment and open.
