### ISSUE TITLE
posterBlocklist not working for premium users

### ISSUE THREAD

**Issue by leanmass** [madingess/EasyApplyBot#18]
hiring_line = job_tile.find_element(By.XPATH, '//span[contains(.,\' is hiring for this\')]')

There is no "is hiring" for premium. 

Also, the job poster title could be anything. 

![image](https://user-images.githubusercontent.com/117451731/210552139-a612d4c3-93c4-43ce-aafa-2da92e2ff093.png)

**Comment by madingess** [comment]
Interesting insight. I've never used the premium version so I've never seen this "Meet the hiring team" section. Currently the poster blacklist looks for posters names appearing as follows:
![image](https://user-images.githubusercontent.com/20915605/210590781-9e216a79-bd36-4cc1-b9e5-545e4698cd52.png)

I'll see what I can do to add in functionality for filtering from that display as well.

**Comment by madingess** [comment]
For anyone tracking along, see the thread linked above in the mention at https://github.com/voidbydefault/EasyApplyBot/issues/16
