### ISSUE TITLE
Linked in no longer uses classes like fb-form-element-label 

### ISSUE THREAD

**Issue by madingess** [madingess/EasyApplyBot#2]
Per @Briwhee [here](https://github.com/NathanDuma/LinkedIn-Easy-Apply-Bot/issues/64#issuecomment-1341260112)

> Linked in no longer uses classes like fb-form-element-label so that repository doesn't work. It was a change made about two days ago. I tried to raise an issue there, but couldn't find where so I raised it here.

**Comment by madingess** [comment]
Will verify and investigate today

**Comment by Briwhee** [comment]
HTML for text answers 
<div data-test-single-line-text-form-component="">
  <div id="ember1868" class="artdeco-text-input artdeco-text-input--type-text artdeco-text-input--color-default artdeco-text-input--state-required ember-view">  <div id="ember1869" class="artdeco-text-input--container ember-view">  <label for="single-line-text-form-component-formElement-urn-li-jobs-applyformcommon-easyApplyFormElement-3275860193-69737661-numeric" class="artdeco-text-input--label">How many years of work experience do you have with Jamf?</label>
  <input class=" artdeco-text-input--input" id="single-line-text-form-component-formElement-urn-li-jobs-applyformcommon-easyApplyFormElement-3275860193-69737661-numeric" required="" aria-describedby="single-line-text-form-component-formElement-urn-li-jobs-applyformcommon-easyApplyFormElement-3275860193-69737661-numeric-error" type="text">
</div>
</div>

  <div id="single-line-text-form-component-formElement-urn-li-jobs-applyformcommon-easyApplyFormElement-3275860193-69737661-numeric-error">
</div>
</div>

**Comment by madingess** [comment]
It's now updated to work with the new linkedin webpage and to hopefully be more robust so future changes aren't necessarily breaking. 

Please open a new issue if you continue experiencing issues @Briwhee
