### ISSUE TITLE
Unintended behavior once "No matching jobs found" page is reached

### ISSUE THREAD

**Issue by voidbydefault** [madingess/EasyApplyBot#20]
Bot goes into infinite click loop once:

1. there are no Easy Apply jobs are left, a page with text "No matching jobs found" is reached; and
2. A section "jobs you may be interested in" appears.

Usually, "jobs you may be interested in" is a non-Easy Apply job leading to employer's webpage for application that's where the bot starts sending clicks on "apply" opening an infinite array of new tabs.

Edits:

1. Screenshots:
a. https://ibb.co/tYjGkN4
b. https://ibb.co/wMF7zfQ

2. How to reproduce? Let the bot run until no Easy Apply jobs are left.

**Comment by madingess** [comment]
This seems to working after your changes were included, at least I've been unable to reproduce the error when reaching this page. 

Please reopen if you find this still occurs!
