### ISSUE TITLE
Why is minimum_page_time 15 minutes?

### ISSUE THREAD

**Issue by JediRhymeTrix** [madingess/EasyApplyBot#21]
It seems excessive. This is resulting in the bot halting for over 12 minutes between pages or after throwing an error. Especially when the bot is re-run on a filter set for which most of the jobs on the first few pages have already been applied to, the throughput becomes really low. For example, I left it running overnight for around 8 hours and it only applied to ~30 jobs. It would be faster to apply manually in that case, wouldn't it?

**Comment by RedmondMann** [comment]
I think this code is abandoned and no longer works.

**Comment by JediRhymeTrix** [comment]
Well, it does work, but I can see that it is no longer in development. I've been working on a lot of QoL improvements for this project locally but haven't decided whether to polish them and publish to my own fork.

Anyway, I'm gonna go ahead and close this issue.
