### ISSUE TITLE
I hope this project is not abandoned.  Such an incredible tool 

### ISSUE THREAD

**Issue by RedmondMann** [madingess/EasyApplyBot#22]
Won't log into LinkedIn

**Comment by RedmondMann** [comment]
Also there are some YAML issues.  You need to change "Experience" to "Industry" or something in the requirements section

**Comment by voidbydefault** [comment]
> Also there are some YAML issues. You need to change "Experience" to "Industry" or something in the requirements section

No change requires. Working for me. Ensure you didn't add any unwanted space or line break (enter) in config.yaml

Please mark the issue as closed as issue is unrelated to the tool. Thanks.

**Comment by RedmondMann** [comment]
Interesting

**Comment by madingess** [comment]
I echo @voidbydefault 's comment. This is continuing to function as expected. 

If you continue to see issues with the login and can provide more details, please reopen this issue!

**Comment by RedmondMann** [comment]
What is this in response to?  9 months later I have completely forgot haha
