### ISSUE TITLE
New Chrome update breaks the script

### ISSUE THREAD

**Issue by KenWuqianghao** [madingess/EasyApplyBot#23]
It was working on May 2nd and after the update, it gives me this error

```
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 113
Current browser version is 112.0.5615.49 with binary path /snap/bin/chromium
```

**Comment by voidbydefault** [comment]
> It was working on May 2nd and after the update, it gives me this error
> 
> ```
> supports Chrome version 113
> Current browser version is 112.0.5615.49 with binary path /snap/bin/chromium
> ```

Check your Chrome version 113. It seems you are on Linux so sync your distribution's repo and do a system update. Webdriver gets updated faster in upstream compared to some Linux distributions. Marked as close once done. Thanks.

**Comment by madingess** [comment]
Dear @KenWuqianghao ,

Thank you for the report. This should be a versioning issue. I'll include some details in the setup section of the README which should help avoid this. 

Thanks to @voidbydefault for his response here too!
