### ISSUE TITLE
Webdriver got multiple values 

### ISSUE THREAD

**Issue by iakramdurrani** [madingess/EasyApplyBot#25]
driver = webdriver.Chrome(ChromeDriverManager().install(), options=browser_options)
TypeError: WebDriver.__init__() got multiple values for argument 'options'

i just installed this but i am unable to run it. 

can anyone assist on this error. thanks

**Comment by iakramdurrani** [comment]
this is what i see, 

/Users/akramdurrani/PycharmProjects/LinkedIn-Easy-Apply-Bot/venv/bin/python /Users/akramdurrani/PycharmProjects/LinkedIn-Easy-Apply-Bot/main.py 
Traceback (most recent call last):
  File "/Users/akramdurrani/PycharmProjects/LinkedIn-Easy-Apply-Bot/main.py", line 123, in <module>
    browser = init_browser()
  File "/Users/akramdurrani/PycharmProjects/LinkedIn-Easy-Apply-Bot/main.py", line 16, in init_browser
    driver = webdriver.Chrome(ChromeDriverManager().install(), chrome_options=browser_options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'chrome_options'

Process finished with exit code 1

a response will be much appreciated. thank you

**Comment by OsricDhoubhadel** [comment]
I get the same issue. Please let me know if you find a way to resolve this

**Comment by voidbydefault** [comment]
This repo has been abandoned, I have forked it for maintenance. Get new code from (https://github.com/voidbydefault/EasyApplyBot/)

**Comment by madingess** [comment]
Greetings folks, 

I've decided to give this neglected some attention. You should find it properly maintained once more. You should find this issue fixed. Credits to @okazaki0 for his contribution on this one. 

Please reopen with details if you continue to encounter this issue.
