### ISSUE TITLE
TypeError: WebDriver.__init__() got multiple values for argument 'options'

### ISSUE THREAD

**Issue by tgila2505** [madingess/EasyApplyBot#28]
Original Code:

![image](https://github.com/madingess/EasyApplyBot/assets/139653377/9d7eaec3-ada2-4923-a77e-c9f0e947eaf5)

Error:

![image](https://github.com/madingess/EasyApplyBot/assets/139653377/eea9501b-a094-4d3c-80b6-faaac5696274)

Issue:
Bot does not execute, please help.

**Comment by voidbydefault** [comment]
This repo has been abandoned, I have forked it for maintenance. Get new code from (https://github.com/voidbydefault/EasyApplyBot/)

**Comment by madingess** [comment]
For those tracking along, @voidbydefault 's changes have been merged into this repository. 

This should be working once more.

Thank you!
