### ISSUE TITLE
How to run this on macbook

### ISSUE THREAD

**Issue by gowarrior** [madingess/EasyApplyBot#35]
Tried to run this on macbook using python3 main.py the Chrome web page shows but nothing progress. Can you help explain why?

**Comment by azjz92** [comment]
First off be patient, Im running into some speed issues on OSX, once you run it just leave your computer alone for 10 mins and see what happens, then stop the code and copy and paste the output log here or into chatgpt and troubleshoot, I had a lot of issues with my config yaml where I stupidly had all falses in some of the boolean sections,

**Comment by azjz92** [comment]
I'm evaluating all the linkedinbots to determine the best one though, this one seems like the most potential so far so I want to get it working properly

**Comment by madingess** [comment]
Dear @gowarrior ,

Thanks for raising this. Unfortunately I don't have a Mac OS machine in order to reproduce this. 

Will you please share your console log and log files and any errors which may be present?

**Comment by madingess** [comment]
Please reopen this issue if you revisit this with additional details
