### ISSUE TITLE
Error when running main.py

### ISSUE THREAD

**Issue by sergejnico1111** [madingess/EasyApplyBot#37]
When I run the main.py file, I get this error (I edited the location for this comment):
Traceback (most recent call last):
  File "Main.py FILE LOCATION", line 1, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by wienerman69** [comment]
If you are on Python, go to your terminal and type in pip install pyyaml

**Comment by voidbydefault** [comment]
Install dependencies mentioned in `requirements.txt`. Note an issue.

**Comment by madingess** [comment]
The Getting Started section of the README should cover this. Closing this. Thanks @wienerman69 and @voidbydefault for the responses.
