### ISSUE TITLE
Country code Canada (+1) not found! Make sure it is exact. Could not input phone number. 

### ISSUE THREAD

**Issue by logix727** [madingess/EasyApplyBot#4]
Applying to the job....
Country code Canada (+1) not found! Make sure it is exact.
Could not input phone number.
Country code Canada (+1) not found! Make sure it is exact.

**Comment by logix727** [comment]
gets stuick when trying to start application

**Comment by Briwhee** [comment]
This is the same issue with Issue #1 that I posted.

**Comment by madingess** [comment]
I am not able to reproduce this issue, even when I leave that [line in the configuration file](https://github.com/madingess/EasyApplyBot/blob/master/config.yaml#L150) unchanged.

Since there have been a number of issues arise related to varying package and python versions, I added a virtual environment to the project tracking. Will you please try again using the updated [Setup & Startup section of the README](https://github.com/madingess/EasyApplyBot/blob/master/README.md#setup--startup) to see if this issue persists?

**Comment by logix727** [comment]
Will re check when home tomorrow

**Comment by logix727** [comment]
t-master$ source venv/bin/activate
bash: venv/bin/activate: No such file or directory

**Comment by madingess** [comment]
To run the bot, **open the command line in the cloned repository directory**. Activate the virtual environment and start the bot using these commands:
```bash
source venv/bin/activate
python3 main.py
```

You need to change your directory to the folder where you store the repository.

**Comment by madingess** [comment]
If I recall correctly the virtual environment uses 3.6.8

**Comment by madingess** [comment]
Also, this exception should not halt functionality. It should leave selected whatever country code was previously selected, then continue to enter the remaining information. Does it stop the application entirely when you see this output?

**Comment by logix727** [comment]
correct it breaks it as it cannot add the phone number next  let me try with the comment

**Comment by logix727** [comment]
Country code Canada (+1) not found! Make sure it is exact.
Could not input phone number.
with line 721 commented. im gonna purge my python install and reinstall to see if that helps

**Comment by logix727** [comment]
![image](https://user-images.githubusercontent.com/18837830/206515593-f2864c04-ef6e-477f-adb8-7d7092ab9cba.png)

**Comment by madingess** [comment]
That is a new presentation, but likely for the same error. Will you please share a screenshot with the following: right-click the phone number input box and choose inspect. Please include the `class` attribute in the screenshot. An example:
![scrn](https://user-images.githubusercontent.com/20915605/206518674-8d0cc69d-8345-400f-9936-483484586302.png)


If you are indeed in Canada, you may be getting served a linkedin page which uses different values for the `class` attributes. The screenshot should help. Also, is your URL ca.linkedin.com?

**Comment by logix727** [comment]
sure can not in canada in us dont mind the canada default

![image](https://user-images.githubusercontent.com/18837830/206521804-e52058b7-b777-4fee-981c-9cbdede5b805.png)
here is 

![image](https://user-images.githubusercontent.com/18837830/206521953-f78ee805-8f69-451c-b3e0-de97037ecae1.png)


<input class=" artdeco-text-input--input" id="single-line-text-form-component-formElement-urn-li-jobs-applyformcommon-easyApplyFormElement-3391844020-76853307-phoneNumber-nationalNumber" required="" aria-describedby="single-line-text-form-component-formElement-urn-li-jobs-applyformcommon-easyApplyFormElement-3391844020-76853307-phoneNumber-nationalNumber-error" type="text">

**Comment by madingess** [comment]
Thank you. Oddly the `class` attribute in your page is different from mine. I am also in the US. 

That said, this may be enough to change the way it looks for these fields in a way which works for both of us. I made need this same information for other fields, but let's see what happens if I can fix the phone number input first.

**Comment by logix727** [comment]
cool let me know what i can do to help

**Comment by madingess** [comment]
Luckily the day after this conversion occurred it started serving me the new webpage. I've now updated it to work with the new linkedin webpage and hopefully be more robust so future changes aren't necessarily breaking. 

Please try it again and let me know.

**Comment by madingess** [comment]
Please reopen if the issue persists.
