### ISSUE TITLE
Speed Issue, 5 mins per app?

### ISSUE THREAD

**Issue by azjz92** [madingess/EasyApplyBot#40]
<img width="455" alt="Screen Shot 2024-07-31 at 4 57 32 PM" src="https://github.com/user-attachments/assets/ad8c5606-75c4-4443-8103-bad163557ee1">
i seem to be having extremely slow speeds, and wondering if i'm doing something wrong, we have variations in speed for up to 10 minutes per app. Obviously this project is incredible and I've been comparing it too other github bots, but so far thats the only weakness I've detected. Let me know if you have any ideas or what sort of speeds to expect if the bot is working perfectly. Thank you!!

Attached is an image of my recent output.csv data, note the time

**Comment by madingess** [comment]
Dear @azjz92 ,

Thank you for your kind words.

There are a number of `sleep()` statements throughout the code in the `source/app/linkedineasyapply.py` with wait times designed to circumvent LinkedIn's bot detection software.

Changing or removing these wait times will reduce the time taken to perform each step of the application process. As always, proceed at your own risk.
