### ISSUE TITLE
Unable to find web element

### ISSUE THREAD

**Issue by voidbydefault** [madingess/EasyApplyBot#41]
Hi @madingess ,

Need some help if you could have a look at issue https://github.com/voidbydefault/EasyApplyBot/issues/66 which appears to be affecting some regions only where the bot fails at this line (unable to find web element):

` job_el = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title') `

https://github.com/voidbydefault/EasyApplyBot/blob/eb810bbe5a76302d26642e358b638990a5c987b9/linkedineasyapply.py#L227

I have tested bot on my account as well as another test account (both from Middle East), it works fine but at least two users reported 'element not found issue' from India and Pakistan.

I have spent about 18 hours trying to use CLASS, XPATH, and CSS selectors but it's not working -- so probably beyond my current level of expertise. Can yo please have a look? 

Thanks.

**Comment by KOKOSde** [comment]
use 

job_el = job_tile.find_element(By.XPATH, '//a[contains(@class, "job-card-job-posting-card-wrapper__card-link")]')


worked for me

**Comment by voidbydefault** [comment]
Thanks, tried and outcome is as follows:

1. My Middle Eastern (ME) test account = fails, bot can't find it and crashes.
2. My Asian test account = works but after applying on the first job it gets stuck on the job just applied for.

Starting the job application...
Application sent to  for the position of .
updated output.csv.
An application for a job at  has been submitted earlier.
updated output.csv.
An application for a job at  has been submitted earlier.
updated output.csv.
An application for a job at  has been submitted earlier.
...
...
An application for a job at  has been submitted earlier.
updated output.csv.
(I manually clicked on next job and then...)
... Starting the job application...
Updated unprepared_questions.csv with ['text', 'how many years of work experience do you have with software as a service (saas)?'].
```

It moves on to the next job in queue once clicked manually.  Seems regional profile issue, needs more work. God damn Linkedin.
