### ISSUE TITLE
Backend change in Linkedin job search page causes bot to break

### ISSUE THREAD

**Issue by voidbydefault** [madingess/EasyApplyBot#42]
Hi @madingess , I am unable to get a hold of subject issue. Can you please have a look at details/screenshots here and suggest ideas?

https://github.com/voidbydefault/EasyApplyBot/issues/71

Thanks.

**Comment by madingess** [comment]
Dear @voidbydefault , 

It's good to hear from you, despite the unfortunate circumstance. While I haven't looked into this beyond reading your linked issue, I recall there may be a way to use XPATH from a relative location in the DOM. 

I understand your incentive to get it working again for those following your youtube tutorial. I hope to find some time by the end of the year to fix the issue in this repo.

It's almost as if LinkedIn doesn't want us botting on their website :)

**Comment by logix727** [comment]
Hello m8's they also introduced a limit to how many applications

**Comment by voidbydefault** [comment]
> I understand your incentive to get it working again for those following your youtube tutorial.

Not really, it's more to help people when inflation and cost of living is highest in decades. Just to set it straight, I have been handling this project since 2021 and posted on YT sometime in 2022 after repeated "how to setup" questions so YT isn't any incentive or motivation. 

> I hope to find some time ...

I asked you only after spending 20+ some hours after failing a bunch of trial-error solutions.

> XPATH

I managed to fix it but it leads to other issues.
