### ISSUE TITLE
 DeprecationWarning: use options instead of chrome_options

### ISSUE THREAD

**Issue by logix727** [madingess/EasyApplyBot#6]
DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install(), chrome_options=browser_options)
/home//Desktop/EasyApplyBot-master/main.py:16: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(ChromeDriverManager().install(), chrome_options=browser_options)

issue still persists

**Comment by madingess** [comment]
Will you please confirm that you are using the virtual environment in the repository? My understanding is that these warnings should only occur for certain versions of Selenium.

Instructions for activating the virtual environment  are listed in the README.

Example:
![Screenshot from 2022-12-14 15-46-49](https://user-images.githubusercontent.com/20915605/207710402-a8c5a3cd-0203-4fc6-8d56-97a61b64f412.png)

**Comment by logix727** [comment]
I did both vnev and latest python etc I had it fixed on the em other bot
you forked from lemme look at the code.

**Comment by madingess** [comment]
I'm confused by the response. Are these warnings occurring when running the bot from this repository while in the virtual environment?

**Comment by voidbydefault** [comment]
> Are these warnings occurring when running the bot from this repository while in the virtual environment?

Yes, MeToo. Created a pull request, please accept and close the issue.

**Comment by madingess** [comment]
Closing since https://github.com/madingess/EasyApplyBot/pull/13 has been merged.
