### ISSUE TITLE
breaks when cant apply 

### ISSUE THREAD

**Issue by logix727** [madingess/EasyApplyBot#8]
#20 0x7f5f4e494b43 <unknown>

Could not apply to the job!
Applying to jobs on this page has been completed!
Sleeping for 670.3622999191284 seconds.

**Comment by madingess** [comment]
Yeah. This is some weird behavior leftover from the previous developer/maintainer of the project. To me it seems that the bot should skip this the failing application and continue to the next.

I'll bust this out tomorrow. Hopefully I'll be able to address the other issues too.

**Comment by madingess** [comment]
This long sleep time should no longer occur if the bot fails to apply to a listing. It will still sleep if left running for a long time or if it runs out of listing to which it can apply.

Please reopen here if this issue continues.
